// source: Material UI components and styling - https://mui.com/
// source: Material UI icons - https://mui.com/material-ui/material-icons/

import React from "react";
import { Box, Typography, Paper } from "@mui/material";
import PeopleIcon from "@mui/icons-material/People";

// props interface for waiting room screen
// this screen displays after player 1 creates a room and is waiting for player 2 to join
interface WaitingRoomProps {
  roomCode: string | null; // unique 6-character room code generated by server, null if not set
  playerCount: number; // current number of players in the room (0 - 2)
}

// waiting room component: displays room code and player count while waiting for second player
// player 1 sees this screen after creating a room
// shows the room code that needs to be shared with player 2
// automatically transitions to input phase when second player joins
export function WaitingRoom({ roomCode, playerCount }: WaitingRoomProps) {
  return (
    // full-screen container with gradient background
    // uses fixed positioning to cover entire viewport
    <Box
      sx={{
        minHeight: "100vh",
        width: "100vw",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "linear-gradient(135deg, #fff7ed 0%, #fdf2f8 50%, #fef2f2 100%)",
        padding: 0,
        margin: 0,
        position: "fixed",
        top: 0,
        left: 0,
      }}
    >
      {/* centered white card containing all UI elements */}
      <Paper
        elevation={3}
        sx={{
          maxWidth: 500,
          width: "100%",
          padding: 5,
          borderRadius: 6,
          textAlign: "center",
        }}
      >
        {/* main title */}
        <Typography variant="h4" gutterBottom>
          Waiting Room
        </Typography>
        
        {/* instruction text telling user to share the code */}
        <Typography variant="body1" color="text.secondary" sx={{ mb: 5 }}>
          Share this code with your friend
        </Typography>

        {/* label for room code display */}
        <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
          Room Code
        </Typography>

        {/* room code display box with colored background */}
        {/* uses letter spacing for better readability of the code */}
        <Box
          sx={{
            backgroundColor: "#fef3f0",
            borderRadius: "16px",
            padding: "16px 32px",
            display: "inline-block",
            mb: 4,
          }}
        >
          {/* displays the 6-character room code in large, spaced-out text */}
          <Typography variant="h5" fontWeight="600" letterSpacing={2}>
            {roomCode}
          </Typography>
        </Box>

        {/* player count indicator with people icon */}
        {/* shows "1/2 Players" when waiting, "2/2 Players" when both joined */}
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            gap: 1,
            mb: 3,
          }}
        >
          <PeopleIcon sx={{ color: "text.secondary", fontSize: 24 }} />
          <Typography variant="body1" color="text.secondary">
            {playerCount}/2 Players
          </Typography>
        </Box>

        {/* waiting message shown until second player joins */}
        <Typography variant="body2" color="text.secondary">
          Waiting for another player to join...
        </Typography>
      </Paper>
    </Box>
  );
}